const topics = [
  'AI in Adult Learning',
  'AI in Consulting',
  'AI in Project Management',
  'Business Development in Technical Services',
  'Candid Communication',
  'Career Development in Technical Services',
  'Client Experience',
  'Client Feedback Software',
  'Client Interactions',
  'Closing a Project Strategically',
  'Competitor Intelligence A License to Differentiate',
  'Conducting Color Reviews of Proposals',
  'Conducting Market Research',
  'Creativity and Innovation',
  'Cross Selling in Multi-Disciplinary Firms',
  'CRM Software',
  'Cures for Operational Headaches',
  'Designing a Proposal Process',
  'Emotional Intelligence',
  'Employee Experience',
  'Finding Projects Before they Become RFPs',
  'Integrated Project Delivery or IPD',
  'Leadership in Technical Consulting',
  'Leading Change',
  'Leading Groups and Creating Content on Twennie',
  'Making a Proposal Easy to Read, Skim, and Evaluate',
  'Making Safety a Part of Your Culture',
  'Managing Scope So It Doesnt Manage You',
  'Mental Health in Consulting Environments',
  'Never Let Good Data Get Away Business Development',
  'Never Let Good Data Get Away Project Management',
  'Non-Technical Roles in Technical Environments',
  'People Before Profit',
  'Program Management',
  'Project Management',
  'Project Management Software',
  'Proposal Management',
  'Proposal Pricing Strategies',
  'Proposal Strategy',
  'Pull Marketing',
  'Pursuing the Right Projects for Your Firm and Your Team',
  'Remote and Hybrid Work',
  'Rescuing a Project That Has Gone Off the Rails',
  'Risk Management',
  'Social Entrepreneurship',
  'Social Media, Advertising, and Other Mysteries',
  'Soft Skills in Technical Environments',
  'Storytelling in Technical Marketing',
  'Team Building in Technical Consulting',
  'The Advantage of Failure',
  'The First 10 Days of a Project',
  'The Pareto Principle',
  'The Power of Play in the Workplace',
  'The Power of Purpose',
  'Tips and Tricks for Proposal Proofreading',
  'Turning a Project into a Business Development Powerhouse',
  'UnCommoditizing Your Services by Delivering What Clients Truly Value',
  'Using Lean in Project Management',
  'When the Workload is Light',
  'Workplace Culture'
];

module.exports = topics;